server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: 'ldamuleli'
    password: 'lodav72#'
    url: jdbc:postgresql://localhost:5432/fraud
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
  zipkin:
    base-url: http://localhost:9411
    hibernate:
      ddl-auto: update
    show-sql: 'true'

